name: License scan on PR

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    name: Perform license scan
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: License check
      id: compliance
      uses: GMishx/fossology-action@main
      with:
        scan_mode: 'repo'
        scanners: 'nomos ojo'
        report_format: 'SPDX_JSON'
  copyright_check:
    runs-on: ubuntu-latest
    name: Perform copyright scan
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: License check
      id: compliance
      uses: GMishx/fossology-action@main
      with:
        scan_mode: ''
        scanners: 'copyright keyword'
        report_format: 'SPDX_YAML'
    - name: 'Upload report'
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: Scan results
        path: results
