# SPDX-FileCopyrightText: © 2021 Avinal Kumar <avinal.xlvii@gmail.com>
# SPDX-FileCopyrightText: © 2025 kaushlendra-pratap.singh@siemens.com

# SPDX-License-Identifier: GPL-2.0-only AND LGPL-2.1-only

name: Static checks and analysis

concurrency:
  group: static-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  syntax-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          echo PATH="/usr/lib/ccache/:$PATH" >> $GITHUB_ENV
          echo COMPOSER_HOME="$HOME/.composer/" >> $GITHUB_ENV
      - uses: actions/checkout@v5
        with:
          fetch-depth: 50
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: gettext, mbstring, gd, json, xml, zip, pgsql, curl, uuid, posix, sqlite3
      - name: Syntax Check
        run: |
          bash src/testing/syntax/syntaxtest.sh
      - name: Composer check on PHP 7.4
        run: composer validate --no-check-all --working-dir=src --strict
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gettext, mbstring, json, xml, pgsql, curl, uuid, posix, sqlite3
      - name: Composer check on PHP 8.1
        run: composer validate --no-check-all --working-dir=src --strict

  code-analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
          echo PATH="/usr/lib/ccache/:$PATH" >> $GITHUB_ENV

      - uses: actions/checkout@v5
        with:
          fetch-depth: 50
      - name: Static Code Analysis
        run: cppcheck -q -isrc/nomos/agent_tests/testdata/NomosTestfiles/ -isrc/testing/dataFiles/ src/

  codesniffer:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gettext, mbstring, gd, json, xml, zip, pgsql, curl, uuid, posix, sqlite3
      - uses: actions/checkout@v5
        with:
          fetch-depth: 50
      - name: PHP Codesniffer
        run: |
          export COMPOSER_HOME="$HOME/.composer/"
          composer install --prefer-dist --working-dir=src
          composer --working-dir=src run-script phpcs

  copy-paste:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gettext, mbstring, gd, json, xml, zip, pgsql, curl, uuid, posix, sqlite3, dom
          tools: sebastian/phpcpd:6.0.3
      - uses: actions/checkout@v5
        with:
          fetch-depth: 50
      - name: Copy/Paste detector
        run: |
          export COMPOSER_HOME="$HOME/.composer/"
          composer install --prefer-dist --working-dir=src
          sudo phpdismod -v ALL -s ALL xdebug
          phpcpd src/cli/ src/copyright/ src/decider*/ src/lib/ src/monk/ src/nomos/ src/readmeoss/ src/spdx/ src/www/ || echo -e "\033[0;31mDuplication detected: Task Failed"

  openapi-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup default rules
        run: |
          echo '{"extends": ["spectral:oas"]}' > .spectral.json
      - name: Run spectral
        uses: stoplightio/spectral-action@v0.8.12
        with:
          file_glob: src/www/ui/api/documentation/openapi.yaml

  REUSE-Compliance-Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v6

  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Ensure Commit-Lint Config Exists
        run: |
          if [ ! -f "commitlint.config.mjs" ]; then
            echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.mjs
          fi

      - name: Run Commit Lint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ./commitlint.config.mjs

      - name: DCO Check
        uses: christophebedard/dco-check@0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --exclude-pattern '.*dependabot\[bot\]@users\.noreply\.github\.com'

