# Copyright 2021 Anupam Ghosh <ag.4ums@gmail.com>,
#   Gaurav Mishra <gmishx@gmishx.in>
# SPDX-License-Identifier: GPL-2.0 AND LGPL-2.1

name: c tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  C-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4'] # Can be extended in future
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcppunit-dev
          sudo ./utils/fo-installdeps -y -e
          export PATH="/usr/lib/ccache/:$PATH"

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, gd, xml, zip, json, sqlite3, curl
        env:
          fail-fast: true

      - name: Setup test database
        env:
          PGHOST: 127.0.0.1
          PGPORT: 5432
        run: |
          ./utils/prepare-test -afty

          #remove test all as delagent is failing
      - name: Unit tests
        env:
          PGHOST: 127.0.0.1
          PGPORT: 5432
        run: |
          make all phpvendors test-cli test-copyright test-lib test-monk \
          test-nomos test-ojo test-reuser test-scheduler test-spdx2 \
          test-unifiedreport test-www
